/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejl.testetecnicojl.Visao;

import testejl.testetecnicojl.Modelo.RN.GenericRN;
import testejl.testetecnicojl.Modelo.VO.Produto;

/**
 *
 * @author Jece Xavier
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
//        this.validacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jdkpHome = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmbProduto = new javax.swing.JMenu();
        jmbiProdutoCadastar = new javax.swing.JMenuItem();
        jmbiProdutoEditar = new javax.swing.JMenuItem();
        jmbEstoque = new javax.swing.JMenu();
        jmbiEstoqueEntrada = new javax.swing.JMenuItem();
        jmbiEstoqueSaida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setLayout(null);

        jdkpHome.setBackground(null);

        javax.swing.GroupLayout jdkpHomeLayout = new javax.swing.GroupLayout(jdkpHome);
        jdkpHome.setLayout(jdkpHomeLayout);
        jdkpHomeLayout.setHorizontalGroup(
            jdkpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jdkpHomeLayout.setVerticalGroup(
            jdkpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        panelPrincipal.add(jdkpHome);
        jdkpHome.setBounds(0, 0, 500, 470);

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 480));

        jmbProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProduto.png"))); // NOI18N
        jmbProduto.setText("Produtos");

        jmbiProdutoCadastar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProdutoCadastro.png"))); // NOI18N
        jmbiProdutoCadastar.setText("Cadastar Produto");
        jmbiProdutoCadastar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmbiProdutoCadastarMouseClicked(evt);
            }
        });
        jmbiProdutoCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbiProdutoCadastarActionPerformed(evt);
            }
        });
        jmbProduto.add(jmbiProdutoCadastar);

        jmbiProdutoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProdutoLista.png"))); // NOI18N
        jmbiProdutoEditar.setText("Lista Produto");
        jmbiProdutoEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmbiProdutoEditarMouseClicked(evt);
            }
        });
        jmbiProdutoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbiProdutoEditarActionPerformed(evt);
            }
        });
        jmbProduto.add(jmbiProdutoEditar);

        jmbPrincipal.add(jmbProduto);

        jmbEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuEstoque.png"))); // NOI18N
        jmbEstoque.setText("Estoque");

        jmbiEstoqueEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProdutoCadastro.png"))); // NOI18N
        jmbiEstoqueEntrada.setText("Cadastrar");
        jmbiEstoqueEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbiEstoqueEntradaActionPerformed(evt);
            }
        });
        jmbEstoque.add(jmbiEstoqueEntrada);

        jmbiEstoqueSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProdutoLista.png"))); // NOI18N
        jmbiEstoqueSaida.setText("Listar");
        jmbiEstoqueSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbiEstoqueSaidaActionPerformed(evt);
            }
        });
        jmbEstoque.add(jmbiEstoqueSaida);

        jmbPrincipal.add(jmbEstoque);

        setJMenuBar(jmbPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmbiProdutoCadastarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbiProdutoCadastarMouseClicked
        
    }//GEN-LAST:event_jmbiProdutoCadastarMouseClicked

    private void jmbiProdutoEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbiProdutoEditarMouseClicked

    }//GEN-LAST:event_jmbiProdutoEditarMouseClicked

    private void jmbiProdutoCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbiProdutoCadastarActionPerformed
        ProdutoCRUD telaProduto = new ProdutoCRUD("Cadastro", true);
        this.jdkpHome.add(telaProduto);
        telaProduto.setVisible(true);
    }//GEN-LAST:event_jmbiProdutoCadastarActionPerformed

    private void jmbiProdutoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbiProdutoEditarActionPerformed
        ProdutoList telaProdutoList = new ProdutoList();
        this.jdkpHome.add(telaProdutoList);
        telaProdutoList.setVisible(true);
    }//GEN-LAST:event_jmbiProdutoEditarActionPerformed

    private void jmbiEstoqueEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbiEstoqueEntradaActionPerformed
        MovimentoCRUD telaEstoque = new MovimentoCRUD("Cadastro", true);
        this.jdkpHome.add(telaEstoque);
        telaEstoque.setVisible(true);
    }//GEN-LAST:event_jmbiEstoqueEntradaActionPerformed

    private void jmbiEstoqueSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbiEstoqueSaidaActionPerformed
        MovimentoList telaMovimentoList = new MovimentoList();
        this.jdkpHome.add(telaMovimentoList);
        telaMovimentoList.setVisible(true);
    }//GEN-LAST:event_jmbiEstoqueSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdkpHome;
    private javax.swing.JMenu jmbEstoque;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenu jmbProduto;
    private javax.swing.JMenuItem jmbiEstoqueEntrada;
    private javax.swing.JMenuItem jmbiEstoqueSaida;
    private javax.swing.JMenuItem jmbiProdutoCadastar;
    private javax.swing.JMenuItem jmbiProdutoEditar;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas funções*/
    private void validacao(){
         GenericRN<Produto> produdoRN =new GenericRN<>();
         
         if((produdoRN.listAll(Produto.class)).size() == 0){
             this.jmbiEstoqueEntrada.setEnabled(false);
         }
         
    }

}
