

package testejl.testetecnicojl.Visao;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import testejl.testetecnicojl.Modelo.RN.GenericRN;
import testejl.testetecnicojl.Modelo.VO.MovimentoEstoque;
import testejl.testetecnicojl.Modelo.VO.Produto;

/**
 *
 * @author Jece Xavier
 */
public class MovimentoList extends javax.swing.JInternalFrame {
    
//    Atributos
    
    /**
     * Creates new form ProdutoCRUD
     */
    public MovimentoList( ) {
        initComponents();
        
        this.populaJtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panleFundo = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMoviento = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();

        setClosable(true);

        panleFundo.setLayout(null);

        btnEditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panleFundo.add(btnEditar);
        btnEditar.setBounds(350, 80, 120, 30);

        tblMoviento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Quantidade", "Tipo ", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMoviento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblMovientoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblMoviento);

        panleFundo.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 460, 310);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Movimentação");
        panleFundo.add(lblTitulo);
        lblTitulo.setBounds(0, 10, 480, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 500, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMovientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMovientoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMovientoKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tblMoviento.getSelectedRow()!= -1){
            long id = (long) tblMoviento.getValueAt(tblMoviento.getSelectedRow(), 0);
            
            GenericRN<MovimentoEstoque>  movimentoDAO = new GenericRN<>();
            
            MovimentoEstoque movimento = movimentoDAO.findOne("id", id, MovimentoEstoque.class);
            
            MovimentoCRUD movimentoCRUD = new MovimentoCRUD("Editar", false, movimento);
            this.getDesktopPane().add(movimentoCRUD);
            movimentoCRUD.setVisible(true);
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(null, "Nenhum movimento selecionado :(", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panleFundo;
    private javax.swing.JTable tblMoviento;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas Funções*/
    private void populaJtable(){
        DefaultTableModel modelo = (DefaultTableModel)(tblMoviento.getModel());
        GenericRN<MovimentoEstoque>  movimentoDAO = new GenericRN<>();
        DateTimeFormatter formatadordDataBarra = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        for(MovimentoEstoque m : movimentoDAO.listAll(MovimentoEstoque.class)){
            modelo.addRow(new Object[] {
                m.getId(),
                m.getProduto(),
                (int) m.getQuantidade(),
                m.getTipoMovimento(),
                m.getDataMovimento().format(formatadordDataBarra)
            });
            
        }
        
        tblMoviento.setRowSorter(new TableRowSorter(modelo));
        
        
    }

}
