/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejl.testetecnicojl.Visao;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import testejl.testetecnicojl.Modelo.RN.GenericRN;
import testejl.testetecnicojl.Modelo.VO.MovimentoEstoque;
import testejl.testetecnicojl.Modelo.VO.Produto;

/**
 *
 * @author Jece Xavier
 */
public class MovimentoList extends javax.swing.JInternalFrame {
    
//    Atributos
    private Produto produto;
    
    /**
     * Creates new form ProdutoCRUD
     */
    public MovimentoList( ) {
        initComponents();
        
        this.populaJtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panleFundo = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMoviento = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();

        setClosable(true);

        panleFundo.setLayout(null);

        btnSalvar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSalvar.setText("Editar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panleFundo.add(btnSalvar);
        btnSalvar.setBounds(350, 80, 120, 30);

        tblMoviento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Quantidade", "Tipo ", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMoviento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblMovientoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblMoviento);

        panleFundo.add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 480, 310);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Movimentação");
        panleFundo.add(lblTitulo);
        lblTitulo.setBounds(0, 10, 480, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 500, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMovientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMovientoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMovientoKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(tblMoviento.getSelectedRow()!= -1){
            long id = (long) tblMoviento.getValueAt(tblMoviento.getSelectedRow(), 0);
            String descricao = (String) tblMoviento.getValueAt(tblMoviento.getSelectedRow(), 1);
            int quantidadeMinima = (int) tblMoviento.getValueAt(tblMoviento.getSelectedRow(), 2);
            double valor = (double) tblMoviento.getValueAt(tblMoviento.getSelectedRow(), 3);
            LocalDate dataCadastro = (LocalDate) tblMoviento.getValueAt(tblMoviento.getSelectedRow(), 4); 
            
            produto = new Produto(id, descricao, quantidadeMinima, dataCadastro, valor);
            
            ProdutoCRUD produtoCRUD = new ProdutoCRUD("Editar", produto, false);
            this.getDesktopPane().add(produtoCRUD);
            produtoCRUD.setVisible(true);
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(null, "Nenhum Produto Selecionado :(", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panleFundo;
    private javax.swing.JTable tblMoviento;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas Funções*/
    private void populaJtable(){
        DefaultTableModel modelo = (DefaultTableModel)(tblMoviento.getModel());
        GenericRN<MovimentoEstoque>  movimentoDAO = new GenericRN<>();
        
        for(MovimentoEstoque m : movimentoDAO.listAll(MovimentoEstoque.class)){
            modelo.addRow(new Object[] {
                m.getId(),
                m.getProduto(),
                m.getQuantidade(),
                m.getTipoMovimento(),
                m.getDataMovimento()
            });
            
        }
        
        tblMoviento.setRowSorter(new TableRowSorter(modelo));
        
        
    }

}
