/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejl.testetecnicojl.Visao;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import testejl.testetecnicojl.Modelo.RN.GenericRN;
import testejl.testetecnicojl.Modelo.VO.MovimentoEstoque;
import testejl.testetecnicojl.Modelo.VO.Produto;
import testejl.testetecnicojl.Modelo.VO.TipoMovimentacao;

/**
 *
 * @author Jece Xavier
 */
public class MovimentoCRUD extends javax.swing.JInternalFrame {
    
//    Atributos
    private MovimentoEstoque movimento;
    private boolean telaCadastro;
    
    /**
     * Creates new form ProdutoCRUD
     */
    public MovimentoCRUD(String titulo, boolean telaCadastro ) {
        initComponents();
        
        this.telaCadastro = telaCadastro;
        
        this.setTitle(titulo);

        this.populaCmb();
        
        if(telaCadastro){
            this.lblCodigo.setVisible(false);
            this.txtCodigo.setVisible(false);
        }
    }
    
    public MovimentoCRUD(String titulo, boolean telaCadastro, MovimentoEstoque movimento) {
        initComponents();
        
        this.telaCadastro = telaCadastro;
        
        this.setTitle(titulo);
        
        this.movimento = movimento;
        
        this.populaCmb();
        
        this.populaCampos();

        if(telaCadastro){
            this.lblCodigo.setVisible(false);
            this.txtCodigo.setVisible(false);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblTipoMovimento = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JFormattedTextField();
        lblDataCadastro = new javax.swing.JLabel();
        cmbTipoMovimento = new javax.swing.JComboBox<Object>();
        lblProduto = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        lblQuantidade1 = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox<Object>();

        setClosable(true);

        panelFundo.setLayout(null);

        lblCodigo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCodigo.setText("Código da Movimentação: ");
        panelFundo.add(lblCodigo);
        lblCodigo.setBounds(230, 20, 200, 20);

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelFundo.add(txtCodigo);
        txtCodigo.setBounds(230, 50, 200, 30);

        btnSalvar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panelFundo.add(btnSalvar);
        btnSalvar.setBounds(330, 380, 140, 40);

        lblTipoMovimento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTipoMovimento.setText("Tipo Movimentação:");
        panelFundo.add(lblTipoMovimento);
        lblTipoMovimento.setBounds(300, 180, 160, 30);

        txtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtQuantidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelFundo.add(txtQuantidade);
        txtQuantidade.setBounds(20, 300, 210, 30);

        lblDataCadastro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDataCadastro.setText("Data de Cadastro:");
        panelFundo.add(lblDataCadastro);
        lblDataCadastro.setBounds(20, 110, 140, 20);

        cmbTipoMovimento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelFundo.add(cmbTipoMovimento);
        cmbTipoMovimento.setBounds(260, 220, 200, 30);

        lblProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblProduto.setText("Produto:");
        panelFundo.add(lblProduto);
        lblProduto.setBounds(20, 190, 140, 20);

        txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtData.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelFundo.add(txtData);
        txtData.setBounds(20, 140, 210, 30);

        lblQuantidade1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblQuantidade1.setText("Quantidade: ");
        panelFundo.add(lblQuantidade1);
        lblQuantidade1.setBounds(20, 270, 140, 20);

        cmbProduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelFundo.add(cmbProduto);
        cmbProduto.setBounds(20, 220, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 500, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(this.validarCampos()){
            
            int quatidade = Integer.parseInt(this.txtQuantidade.getText());
           
             DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/MM/yyyy");
             String data = txtData.getText();
             LocalDate dataMovimentacao = LocalDate.parse(data, formatter);
            
            GenericRN<MovimentoEstoque> movitementoRN = new GenericRN<>();
            
            if(telaCadastro){
                
                this.movimento = new MovimentoEstoque(((Produto) cmbProduto.getSelectedItem()), dataMovimentacao, quatidade, ((TipoMovimentacao) cmbTipoMovimento.getSelectedItem()) );
                
                if(movitementoRN.save(this.movimento)){
                    JOptionPane.showMessageDialog(null, "Cadastrado Com Sucesso :)", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao Salvar :(", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                
            }else{
                this.movimento.setDataMovimento(dataMovimentacao);
                this.movimento.setProduto(((Produto) cmbProduto.getSelectedItem()));
                this.movimento.setTipoMovimento(((TipoMovimentacao) cmbTipoMovimento.getSelectedItem()));
                
                if(movitementoRN.update(this.movimento)){
                    JOptionPane.showMessageDialog(null, "Editado Com Sucesso :)", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao Etidar :(", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Dados Invalidos :(", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> cmbProduto;
    private javax.swing.JComboBox<Object> cmbTipoMovimento;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade1;
    private javax.swing.JLabel lblTipoMovimento;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas Funções*/
    private boolean validarCampos(){
        if ( (txtQuantidade.getText().isEmpty()) || (txtData.getText().isEmpty()) ) {
            return false;
        }
        return true;
    }
    
    private void populaCampos(){
        txtCodigo.setText(String.valueOf(movimento.getId()));
        txtData.setText(String.valueOf(movimento.getDataMovimento()));
        txtQuantidade.setText(String.valueOf(movimento.getQuantidade()));
        cmbProduto.setSelectedItem(movimento.getProduto());
        cmbTipoMovimento.setSelectedItem(movimento.getTipoMovimento());
        
    }
    
    private void populaCmb(){
        
        GenericRN<Produto> produdoRN =new GenericRN<>();
        
        for (Produto p : produdoRN.listAll(Produto.class)){
            
            cmbProduto.addItem(p);
        }
        
        cmbTipoMovimento.addItem(TipoMovimentacao.ENTRADA);
        cmbTipoMovimento.addItem(TipoMovimentacao.SAIDA);
    }

}
