/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejl.testetecnicojl.Visao;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import testejl.testetecnicojl.Modelo.RN.GenericRN;
import testejl.testetecnicojl.Modelo.VO.MovimentoEstoque;
import testejl.testetecnicojl.Modelo.VO.Produto;

/**
 *
 * @author Jece Xavier
 */
public class ProdutoList extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form ProdutoCRUD
     */
    public ProdutoList( ) {
        initComponents();
        
        this.populaJtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panleFundo = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();

        setClosable(true);

        panleFundo.setLayout(null);

        btnEditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panleFundo.add(btnEditar);
        btnEditar.setBounds(350, 80, 120, 30);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Quantidade Minima", "Valor", "Cadastrado em"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        panleFundo.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 460, 310);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Produtos");
        panleFundo.add(lblTitulo);
        lblTitulo.setBounds(0, 10, 480, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 500, 470);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProdutoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProdutoKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tblProduto.getSelectedRow()!= -1){
            long id = (long) tblProduto.getValueAt(tblProduto.getSelectedRow(), 0);

            GenericRN<Produto>  produtoDAO = new GenericRN<>();
            
            Produto produto = produtoDAO.findOne("id", id, Produto.class);
            
            ProdutoCRUD produtoCRUD = new ProdutoCRUD("Editar", produto, false);
            this.getDesktopPane().add(produtoCRUD);
            produtoCRUD.setVisible(true);
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado :(", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panleFundo;
    private javax.swing.JTable tblProduto;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas Funções*/
    private void populaJtable(){
        DefaultTableModel modelo = (DefaultTableModel)(tblProduto.getModel());
        GenericRN<Produto>  produtoDAO = new GenericRN<>();
        DateTimeFormatter formatadordDataBarra = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        for(Produto p : produtoDAO.listAll(Produto.class)){
            modelo.addRow(new Object[] {
                p.getId(),
                p.getDrescricao(),
                p.getQuatidadeMinima(),
                p.getValor(),
                p.getDataCadastro().format(formatadordDataBarra)
            });
            
        }
        
        tblProduto.setRowSorter(new TableRowSorter(modelo));
        
        
    }

}
