/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejl.testetecnicojl.Visao;



/**
 *
 * @author Jece Xavier
 */
public class TelaHome extends javax.swing.JFrame {
    
    /*Atributos*/
    TelaMovimentoCRUD tmc;
    TelaMovimentoList tml; 
    
    
    /**
     * Creates new form Home
     */
    public TelaHome() {
        initComponents();
        
        carregandoTelasInternas(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jdkpHome = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmbProduto = new javax.swing.JMenu();
        jmbiProdutoCadastar = new javax.swing.JMenuItem();
        jmbiProdutoLista = new javax.swing.JMenuItem();
        jmbEstoque = new javax.swing.JMenu();
        jmbiMovimentoCadastro = new javax.swing.JMenuItem();
        jmbiMovimentoLista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setLayout(null);

        javax.swing.GroupLayout jdkpHomeLayout = new javax.swing.GroupLayout(jdkpHome);
        jdkpHome.setLayout(jdkpHomeLayout);
        jdkpHomeLayout.setHorizontalGroup(
            jdkpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jdkpHomeLayout.setVerticalGroup(
            jdkpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        panelPrincipal.add(jdkpHome);
        jdkpHome.setBounds(0, 0, 500, 470);

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 480));

        jmbProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProduto.png"))); // NOI18N
        jmbProduto.setText("Produtos");

        jmbiProdutoCadastar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProdutoCadastro.png"))); // NOI18N
        jmbiProdutoCadastar.setText("Cadastar Produto");
        jmbiProdutoCadastar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmbiProdutoCadastarMouseClicked(evt);
            }
        });
        jmbiProdutoCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbiProdutoCadastarActionPerformed(evt);
            }
        });
        jmbProduto.add(jmbiProdutoCadastar);

        jmbiProdutoLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProdutoLista.png"))); // NOI18N
        jmbiProdutoLista.setText("Lista Produto");
        jmbiProdutoLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmbiProdutoListaMouseClicked(evt);
            }
        });
        jmbiProdutoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbiProdutoListaActionPerformed(evt);
            }
        });
        jmbProduto.add(jmbiProdutoLista);

        jmbPrincipal.add(jmbProduto);

        jmbEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuEstoque.png"))); // NOI18N
        jmbEstoque.setText("Estoque");

        jmbiMovimentoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProdutoCadastro.png"))); // NOI18N
        jmbiMovimentoCadastro.setText("Cadastrar");
        jmbiMovimentoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbiMovimentoCadastroActionPerformed(evt);
            }
        });
        jmbEstoque.add(jmbiMovimentoCadastro);

        jmbiMovimentoLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menuProdutoLista.png"))); // NOI18N
        jmbiMovimentoLista.setText("Listar");
        jmbiMovimentoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbiMovimentoListaActionPerformed(evt);
            }
        });
        jmbEstoque.add(jmbiMovimentoLista);

        jmbPrincipal.add(jmbEstoque);

        setJMenuBar(jmbPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmbiProdutoCadastarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbiProdutoCadastarMouseClicked
        
    }//GEN-LAST:event_jmbiProdutoCadastarMouseClicked

    private void jmbiProdutoListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbiProdutoListaMouseClicked

    }//GEN-LAST:event_jmbiProdutoListaMouseClicked

    private void jmbiProdutoCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbiProdutoCadastarActionPerformed
        
    }//GEN-LAST:event_jmbiProdutoCadastarActionPerformed

    private void jmbiProdutoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbiProdutoListaActionPerformed
        
    }//GEN-LAST:event_jmbiProdutoListaActionPerformed

    private void jmbiMovimentoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbiMovimentoCadastroActionPerformed
        this.jdkpHome.setVisible(true);
        this.tmc.setVisible(true);
        this.tmc.setTelaCadastro(true);
    }//GEN-LAST:event_jmbiMovimentoCadastroActionPerformed

    private void jmbiMovimentoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbiMovimentoListaActionPerformed
        this.jdkpHome.setVisible(true);
        this.tml.setVisible(true);
    }//GEN-LAST:event_jmbiMovimentoListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdkpHome;
    private javax.swing.JMenu jmbEstoque;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenu jmbProduto;
    private javax.swing.JMenuItem jmbiMovimentoCadastro;
    private javax.swing.JMenuItem jmbiMovimentoLista;
    private javax.swing.JMenuItem jmbiProdutoCadastar;
    private javax.swing.JMenuItem jmbiProdutoLista;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas funções*/
    private void carregandoTelasInternas(){
//        Instanciando as telas internas
        this.tmc = new TelaMovimentoCRUD("Cadastro", true);
        this.tml = new TelaMovimentoList(this.tmc);
        this.tmc.setTml(tml);
        
//        Adicionando as telas do jdkpHome
        this.jdkpHome.add(tmc);
        this.jdkpHome.add(tml);
        
        
        this.jdkpHome.setVisible(false);
        this.tmc.setVisible(false);
        this.tml.setVisible(false);
    }

}
