/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testejl.testetecnicojl.Visao;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javafx.util.converter.LocalDateStringConverter;
import javax.swing.JOptionPane;
import testejl.testetecnicojl.Modelo.RN.GenericRN;
import testejl.testetecnicojl.Modelo.VO.MovimentoEstoque;
import testejl.testetecnicojl.Modelo.VO.Produto;
import testejl.testetecnicojl.Modelo.VO.TipoMovimentacao;

/**
 *
 * @author Jece Xavier
 */
public class TelaMovimentoCRUD extends javax.swing.JInternalFrame {
    
//    Atributos
    private MovimentoEstoque movimento;
    private boolean telaCadastro;
    private TelaMovimentoList tml;
    
//    Construtor
    public TelaMovimentoCRUD(String titulo, boolean telaCadastro) {
        initComponents();
        
        this.telaCadastro = telaCadastro;
        this.setTitle(titulo);
        this.tml = tml;

        this.populaCmb();
        this.limpaCampos();
        
        if(telaCadastro){
            this.lblCodigo.setVisible(false);
            this.txtCodigo.setVisible(false);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblTipoMovimento = new javax.swing.JLabel();
        lblDataCadastro = new javax.swing.JLabel();
        cmbTipoMovimento = new javax.swing.JComboBox<Object>();
        lblProduto = new javax.swing.JLabel();
        lblQuantidade1 = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox<Object>();
        txtQuantidade = new javax.swing.JFormattedTextField();
        jdcData = new com.toedter.calendar.JDateChooser();
        btnFechar = new javax.swing.JButton();

        setToolTipText("");

        panelFundo.setLayout(null);

        lblCodigo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCodigo.setText("Código da Movimentação: ");
        panelFundo.add(lblCodigo);
        lblCodigo.setBounds(10, 10, 200, 20);

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        panelFundo.add(txtCodigo);
        txtCodigo.setBounds(10, 40, 200, 30);

        btnSalvar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panelFundo.add(btnSalvar);
        btnSalvar.setBounds(330, 380, 140, 40);

        lblTipoMovimento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTipoMovimento.setText("Tipo Movimentação:");
        panelFundo.add(lblTipoMovimento);
        lblTipoMovimento.setBounds(300, 180, 160, 30);

        lblDataCadastro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDataCadastro.setText("Data de Cadastro:");
        panelFundo.add(lblDataCadastro);
        lblDataCadastro.setBounds(20, 110, 140, 20);

        cmbTipoMovimento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelFundo.add(cmbTipoMovimento);
        cmbTipoMovimento.setBounds(260, 220, 200, 30);

        lblProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblProduto.setText("Produto:");
        panelFundo.add(lblProduto);
        lblProduto.setBounds(20, 190, 140, 20);

        lblQuantidade1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblQuantidade1.setText("Quantidade: ");
        panelFundo.add(lblQuantidade1);
        lblQuantidade1.setBounds(20, 270, 140, 20);

        cmbProduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelFundo.add(cmbProduto);
        cmbProduto.setBounds(20, 220, 200, 30);

        txtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panelFundo.add(txtQuantidade);
        txtQuantidade.setBounds(20, 300, 210, 30);

        jdcData.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelFundo.add(jdcData);
        jdcData.setBounds(20, 140, 200, 40);

        btnFechar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        panelFundo.add(btnFechar);
        btnFechar.setBounds(400, 10, 70, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 500, 470);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(this.validarCampos()){
            
//            lendo os dados inseridos
            int quatidade = Integer.parseInt(this.txtQuantidade.getText());
            LocalDate dataMovimentacao = dateToLocalDate(jdcData.getDate());
            Produto prduto = (Produto) cmbProduto.getSelectedItem();
            TipoMovimentacao tm = (TipoMovimentacao) cmbTipoMovimento.getSelectedItem();
            
            GenericRN<MovimentoEstoque> movitementoRN = new GenericRN<>();
            
            if(this.telaCadastro){
                
                this.movimento = new MovimentoEstoque(prduto, dataMovimentacao, quatidade, tm);
                
                if(movitementoRN.save(this.movimento)){
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso :)", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    this.limpaCampos();
                    this.tml.populaJtable();
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao salvar :(", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                
            }else{
                this.movimento.setDataMovimento(dataMovimentacao);
                this.movimento.setProduto(prduto);
                this.movimento.setTipoMovimento(tm);
                
                if(movitementoRN.update(this.movimento)){
                    JOptionPane.showMessageDialog(null, "Editado com sucesso :)", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    this.tml.populaJtable();
                    this.tml.setVisible(true);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao etidar :(", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Dados Invalidos :(", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.setVisible(false);
        this.limpaCampos();
    }//GEN-LAST:event_btnFecharActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> cmbProduto;
    private javax.swing.JComboBox<Object> cmbTipoMovimento;
    private com.toedter.calendar.JDateChooser jdcData;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade1;
    private javax.swing.JLabel lblTipoMovimento;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas Funções*/
    private boolean validarCampos(){
        
        
        
        if ( (this.txtQuantidade.getText().isEmpty()) || (this.cmbProduto.getItemCount() == 0) || (this.cmbTipoMovimento.getSelectedItem() == null) ) {
            return false;
        }else if (dateToLocalDate(this.jdcData.getDate()).isAfter(LocalDate.now()) ){
            return false;
        }else if (dateToLocalDate(this.jdcData.getDate()).isBefore(LocalDate.of(2000, 01, 01)) ){
            return false;
        }else{
            SimpleDateFormat sdff = new SimpleDateFormat("dd/MM/yyyy"); 
            String data = (sdff.format(this.jdcData.getDate()));
            
            int quantidade = Integer.parseInt(this.txtQuantidade.getText());
            
            if(data.isEmpty() || data.equals("")){
                
            }else if(quantidade <= 0){
                return false;
            }
            
        }
        return true;
    }
    
    public void populaCampos(MovimentoEstoque m){
        this.movimento = m;
        
        this.txtCodigo.setText(String.valueOf(this.movimento.getId()));
        this.txtQuantidade.setText(String.valueOf(this.movimento.getQuantidade()));
        this.cmbProduto.setSelectedItem(this.movimento.getProduto());      
        
        this.jdcData.setDate(localDateToDate(this.movimento.getDataMovimento()));

        if(this.movimento.getTipoMovimento().equals(TipoMovimentacao.ENTRADA.getMovimentacao())){
            this.cmbTipoMovimento.setSelectedItem(TipoMovimentacao.ENTRADA);
        }else{
            this.cmbTipoMovimento.setSelectedItem(TipoMovimentacao.SAIDA);
        }
        
    }
    
    private void limpaCampos(){
        this.jdcData.setDate(localDateToDate(LocalDate.now()));
        this.cmbProduto.setSelectedIndex(0);
        this.cmbTipoMovimento.setSelectedIndex(0);
        this.txtQuantidade.setText("");
        
    }
    
    private void populaCmb(){
        
        GenericRN<Produto> produdoRN =new GenericRN<>();
        
        for (Produto p : produdoRN.listAll(Produto.class)){

            this.cmbProduto.addItem(p);
        }

        this.cmbTipoMovimento.addItem(TipoMovimentacao.ENTRADA);
        this.cmbTipoMovimento.addItem(TipoMovimentacao.SAIDA);           
    }
    
    private LocalDate dateToLocalDate(Date d){
        return d.toInstant().atZone( ZoneId.systemDefault() ).toLocalDate();
    }
    
    private Date localDateToDate(LocalDate d){
        return Date.from( d.atStartOfDay( ZoneId.systemDefault() ).toInstant() );

    }
    
    /*Gets and Sets*/

    public boolean isTelaCadastro() {
        return telaCadastro;
    }

    public void setTelaCadastro(boolean telaCadastro) {
        this.telaCadastro = telaCadastro;
    }

    public TelaMovimentoList getTml() {
        return tml;
    }

    public void setTml(TelaMovimentoList tml) {
        this.tml = tml;
    }
    
}
