

package testejl.testetecnicojl.Visao;

import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import testejl.testetecnicojl.Modelo.RN.GenericRN;
import testejl.testetecnicojl.Modelo.VO.MovimentoEstoque;
import testejl.testetecnicojl.Modelo.VO.Produto;

/**
 *
 * @author Jece Xavier
 */
public class TelaInicio extends javax.swing.JInternalFrame {
    
//    Atributos
    
    /**
     * Creates new form ProdutoCRUD
     */
    public TelaInicio() {
        initComponents();
        
        this.populaJtable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panleFundo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();

        panleFundo.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de produtos com estou baixo.");
        panleFundo.add(lblTitulo);
        lblTitulo.setBounds(0, 40, 590, 60);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Qtd.Minima", "Valor ", "Data Cad.", "Qtd. Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        panleFundo.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 560, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        setBounds(0, 0, 601, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProdutoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProdutoKeyReleased

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panleFundo;
    private javax.swing.JTable tblProduto;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas Funções*/
    public void populaJtable(){
        DefaultTableModel modelo = (DefaultTableModel)(tblProduto.getModel());
        modelo.setNumRows(0);
        GenericRN<Produto>  produtoRN = new GenericRN<>();
        DateTimeFormatter formatadordDataBarra = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        
        int quantidadeProdutosCadastrados = 0, quantidadeProdutosBaixo = 0;
        
        for(Produto p : produtoRN.listAll(Produto.class)){
            quantidadeProdutosCadastrados++;
            p.setQuantidade();
            
            if(p.getQuantidade() < p.getQuatidadeMinima()){
                
                quantidadeProdutosBaixo++;
            
                modelo.addRow(new Object[] {
                    p.getId(),
                    p.getDescricao(),
                    p.getQuatidadeMinima(),
                    nf.format(p.getValor()),
                    p.getDataCadastro().format(formatadordDataBarra),
                    p.getQuantidade()
                });
            }
            
        }
        
        tblProduto.setRowSorter(new TableRowSorter(modelo));
        
        if(quantidadeProdutosCadastrados == 0 ){
            this.lblTitulo.setText("Nenhum produto Cadastrado :(");
            this.jScrollPane1.setVisible(false);
        }else if(quantidadeProdutosBaixo == 0){
            this.lblTitulo.setText("Nenhum produto com estoque baixo :)");
            this.jScrollPane1.setVisible(false);
        }else{
            this.lblTitulo.setText(quantidadeProdutosBaixo + " Produto(s) com estoque baixo :(");
            this.jScrollPane1.setVisible(true);
        }
        
        
    }
}
