

package testejl.testetecnicojl.Visao;

import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import testejl.testetecnicojl.Modelo.RN.GenericRN;
import testejl.testetecnicojl.Modelo.VO.MovimentoEstoque;
import testejl.testetecnicojl.Modelo.VO.Produto;

/**
 *
 * @author Jece Xavier
 */
public class TelaProdutoList extends javax.swing.JInternalFrame {
    
//    Atributos
    private TelaProdutoCRUD tpc;
    
    /**
     * Creates new form ProdutoCRUD
     */
    public TelaProdutoList(TelaProdutoCRUD tpc ) {
        initComponents();
        
        this.tpc = tpc;
        
        this.populaJtable();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panleFundo = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        lblPesquisa = new javax.swing.JLabel();

        panleFundo.setLayout(null);

        btnFechar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        panleFundo.add(btnFechar);
        btnFechar.setBounds(500, 10, 70, 23);

        btnPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        panleFundo.add(btnPesquisar);
        btnPesquisar.setBounds(460, 100, 110, 30);

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Produtos");
        panleFundo.add(lblTitulo);
        lblTitulo.setBounds(0, 10, 590, 60);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Qtd.Minima", "Valor ", "Data Cadastrada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        panleFundo.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 560, 380);

        txtPesquisar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panleFundo.add(txtPesquisar);
        txtPesquisar.setBounds(240, 100, 210, 30);

        btnEditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panleFundo.add(btnEditar);
        btnEditar.setBounds(10, 100, 90, 30);

        lblPesquisa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPesquisa.setText("Pesquisar por descrição...");
        panleFundo.add(lblPesquisa);
        lblPesquisa.setBounds(240, 70, 220, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        setBounds(0, 0, 601, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProdutoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProdutoKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       if(this.tblProduto.getSelectedRow()!= -1){
            long id = (long) this.tblProduto.getValueAt(this.tblProduto.getSelectedRow(), 0);
            
            GenericRN<Produto> produtoRN = new GenericRN<>();
            
            Produto produto = produtoRN.findOne("id", id, Produto.class);
            this.abrirTelaEdicao(produto);
        }else{
           JOptionPane.showMessageDialog(null, "Nenhum JOptionPanemovimento selecionado :(", "Falha :(", 0,new ImageIcon(getClass().getResource("/icones/errado.png")));
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panleFundo;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
    
    /*Minhas Funções*/
    public void populaJtable(){
        DefaultTableModel modelo = (DefaultTableModel)(tblProduto.getModel());
        modelo.setNumRows(0);
        GenericRN<Produto>  produtoRN = new GenericRN<>();
        DateTimeFormatter formatadordDataBarra = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        
        for(Produto p : produtoRN.listAll(Produto.class)){
            modelo.addRow(new Object[] {
                p.getId(),
                p.getDescricao(),
                p.getQuatidadeMinima(),
                nf.format(p.getValor()),
                p.getDataCadastro().format(formatadordDataBarra)
            });
            
        }
        
        tblProduto.setRowSorter(new TableRowSorter(modelo));
        
        
    }

    
    private void abrirTelaEdicao(Produto p){
        this.tpc.populaCampos(p);
        this.tpc.setTelaCadastro(false);
        this.tpc.apresentaCampos();
        this.tpc.setVisible(true);
        this.setVisible(false);
    }
}
